# Generated by Django 5.2 on 2025-05-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_venue_event_category_comment_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado'), ('AGOTADO', 'Agotado'), ('TERMINADO', 'Terminado')], default='ACTIVO', max_length=50),
        ),
    ]
