# Generated by Django 5.2 on 2025-04-27 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_notifications_usernotification_notifications_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
