# Generated by Django 5.2 on 2025-04-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
