# Generated by Django 5.2 on 2025-04-30 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app.event'),
        ),
    ]
