# Generated by Django 5.2 on 2025-04-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_ticket_price_remove_ticket_status_ticket_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_ticket',
            field=models.CharField(choices=[('GRL', 'General'), ('VIP', 'VIP')], default='GRL', max_length=3),
        ),
    ]
