# Generated by Django 5.2 on 2025-05-01 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_isdeleted'),
        ('app', '0008_refundrequest'),
    ]

    operations = [
    ]
