# Generated by Django 5.2 on 2025-05-01 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_notification_events'),
        ('app', '0008_refundrequest'),
    ]

    operations = [
    ]
