# Generated by Django 5.2 on 2025-05-02 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_notification_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='events',
            new_name='event',
        ),
    ]
