# Generated by Django 5.2 on 2025-05-02 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_0005_comment_isdeleted_0008_refundrequest'),
        ('app', '0013_alter_notification_priority'),
    ]

    operations = [
    ]
