# Generated by Django 5.2 on 2025-05-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20250502_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
