# Generated by Django 5.2 on 2025-05-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_category_is_deleted_alter_event_category'),
        ('app', '0015_refundrequest_is_deleted'),
    ]

    operations = [
    ]
