# Generated by Django 5.2 on 2025-05-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20250502_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
