name: CD EventHub

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test-unit-integration, test-e2e]  # Asegura que CI haya pasado antes (debes ajustar nombres según tu CI)

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ##- name: Build and push Docker image
      ##  run: |
      ##    docker push eventhub/eventhub:${{ github.ref_name }}

      ##- name: Deploy to Render
      ##  uses: render-examples/deploy-render@v1
      ##  with:
      ##    api_key: ${{ secrets.RENDER_API_KEY }}
      ##    service_id: ${{ secrets.RENDER_SERVICE_ID }}
